// Generated by gencpp from file navigation_msgs/EmergencyStop.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MSGS_MESSAGE_EMERGENCYSTOP_H
#define NAVIGATION_MSGS_MESSAGE_EMERGENCYSTOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace navigation_msgs
{
template <class ContainerAllocator>
struct EmergencyStop_
{
  typedef EmergencyStop_<ContainerAllocator> Type;

  EmergencyStop_()
    : header()
    , emergency_stop(false)  {
    }
  EmergencyStop_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , emergency_stop(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _emergency_stop_type;
  _emergency_stop_type emergency_stop;





  typedef boost::shared_ptr< ::navigation_msgs::EmergencyStop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_msgs::EmergencyStop_<ContainerAllocator> const> ConstPtr;

}; // struct EmergencyStop_

typedef ::navigation_msgs::EmergencyStop_<std::allocator<void> > EmergencyStop;

typedef boost::shared_ptr< ::navigation_msgs::EmergencyStop > EmergencyStopPtr;
typedef boost::shared_ptr< ::navigation_msgs::EmergencyStop const> EmergencyStopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_msgs::EmergencyStop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'navigation_msgs': ['/home/browermb/jmuautonomous/autonomous-navigation/catkin_ws/src/navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_msgs::EmergencyStop_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_msgs::EmergencyStop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_msgs::EmergencyStop_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0ed97528fd0e784408fb431ee7d153c";
  }

  static const char* value(const ::navigation_msgs::EmergencyStop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0ed97528fd0e784ULL;
  static const uint64_t static_value2 = 0x408fb431ee7d153cULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_msgs/EmergencyStop";
  }

  static const char* value(const ::navigation_msgs::EmergencyStop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
bool emergency_stop\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::navigation_msgs::EmergencyStop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.emergency_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmergencyStop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_msgs::EmergencyStop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_msgs::EmergencyStop_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "emergency_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MSGS_MESSAGE_EMERGENCYSTOP_H
