// Generated by gencpp from file navigation_msgs/FErequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MSGS_MESSAGE_FEREQUEST_H
#define NAVIGATION_MSGS_MESSAGE_FEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace navigation_msgs
{
template <class ContainerAllocator>
struct FErequest_
{
  typedef FErequest_<ContainerAllocator> Type;

  FErequest_()
    : starting_location()
    , final_location()
    , header()  {
    }
  FErequest_(const ContainerAllocator& _alloc)
    : starting_location(_alloc)
    , final_location(_alloc)
    , header(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _starting_location_type;
  _starting_location_type starting_location;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _final_location_type;
  _final_location_type final_location;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;





  typedef boost::shared_ptr< ::navigation_msgs::FErequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_msgs::FErequest_<ContainerAllocator> const> ConstPtr;

}; // struct FErequest_

typedef ::navigation_msgs::FErequest_<std::allocator<void> > FErequest;

typedef boost::shared_ptr< ::navigation_msgs::FErequest > FErequestPtr;
typedef boost::shared_ptr< ::navigation_msgs::FErequest const> FErequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_msgs::FErequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_msgs::FErequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'navigation_msgs': ['/home/browermb/jmuautonomous/autonomous-navigation/catkin_ws/src/navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_msgs::FErequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_msgs::FErequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_msgs::FErequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_msgs::FErequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_msgs::FErequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_msgs::FErequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_msgs::FErequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90e91925255dbc49ba4bb3349ffc2807";
  }

  static const char* value(const ::navigation_msgs::FErequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90e91925255dbc49ULL;
  static const uint64_t static_value2 = 0xba4bb3349ffc2807ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_msgs::FErequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_msgs/FErequest";
  }

  static const char* value(const ::navigation_msgs::FErequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_msgs::FErequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string starting_location\n\
string final_location\n\
std_msgs/Header header\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::navigation_msgs::FErequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_msgs::FErequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.starting_location);
      stream.next(m.final_location);
      stream.next(m.header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FErequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_msgs::FErequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_msgs::FErequest_<ContainerAllocator>& v)
  {
    s << indent << "starting_location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.starting_location);
    s << indent << "final_location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.final_location);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MSGS_MESSAGE_FEREQUEST_H
