// Generated by gencpp from file navigation_msgs/LatLongPoint.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MSGS_MESSAGE_LATLONGPOINT_H
#define NAVIGATION_MSGS_MESSAGE_LATLONGPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace navigation_msgs
{
template <class ContainerAllocator>
struct LatLongPoint_
{
  typedef LatLongPoint_<ContainerAllocator> Type;

  LatLongPoint_()
    : header()
    , latitude(0.0)
    , longitude(0.0)
    , elevation(0.0)  {
    }
  LatLongPoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , elevation(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _elevation_type;
  _elevation_type elevation;





  typedef boost::shared_ptr< ::navigation_msgs::LatLongPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_msgs::LatLongPoint_<ContainerAllocator> const> ConstPtr;

}; // struct LatLongPoint_

typedef ::navigation_msgs::LatLongPoint_<std::allocator<void> > LatLongPoint;

typedef boost::shared_ptr< ::navigation_msgs::LatLongPoint > LatLongPointPtr;
typedef boost::shared_ptr< ::navigation_msgs::LatLongPoint const> LatLongPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_msgs::LatLongPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'navigation_msgs': ['/home/browermb/jmuautonomous/autonomous-navigation/catkin_ws/src/navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_msgs::LatLongPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_msgs::LatLongPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_msgs::LatLongPoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff55b7a55dad0e829bbf305901922a70";
  }

  static const char* value(const ::navigation_msgs::LatLongPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff55b7a55dad0e82ULL;
  static const uint64_t static_value2 = 0x9bbf305901922a70ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_msgs/LatLongPoint";
  }

  static const char* value(const ::navigation_msgs::LatLongPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64 latitude\n\
float64 longitude\n\
float64 elevation\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::navigation_msgs::LatLongPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.elevation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LatLongPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_msgs::LatLongPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_msgs::LatLongPoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "elevation: ";
    Printer<double>::stream(s, indent + "  ", v.elevation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MSGS_MESSAGE_LATLONGPOINT_H
